name: Gameflow Containerized CD

on:
  push:
    branches: [$default-branch]
    tags:
      - v*.*.*

  release:
    types: [published]

env:
  registry: eu.gcr.io
  image_name: ${{ github.event.repository.name }}
  service_account: ${{ secrets.GCP_SA }}
  
jobs:
  development:
    if: github.ref == 'refs/heads/$default-branch'
    runs-on: self-hosted
    environment:
      name: development
      url: https://dev.gameflow.dev

    env:
      project_id: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ env.service_account }}
          project_id: ${{ env.project_id }}

      - run: gcloud auth configure-docker -q
        shell: bash

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV
        shell: bash

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ env.project_id }}/${{ env.image_name }}
          tags: |
            type=ref,event=branch
          flavor: |
            latest=auto
            suffix=${{ github.sha }}-${{ env.DATES }}

    - name: Deploy to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  staging:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    environment:
      name: staging
      url: https://stage.gameflow.dev

    env:
      project_id: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ env.service_account }}
          project_id: ${{ env.project_id }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ env.project_id }}/${{ env.image_name }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            latest=auto
            suffix=${{ github.sha }}-${{ env.DATES }}

    - name: Deploy to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  production:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: self-hosted
    environment:
      name: production
      url: https://gameflow.tv

    env:
      project_id: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ env.service_account }}
          project_id: ${{ env.project_id }}

      - run: gcloud auth configure-docker -q

      - run: echo "DATES=$(date "+%s")" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ env.project_id }}/${{ env.image_name }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            latest=auto
            suffix=${{ github.sha }}-${{ env.DATES }}

    - name: Deploy to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
