name: Gameflow Node CI

on:
  push:
    branches: ["**"]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint:ci

      - name: check formatting
        run: npm run format:ci

  compile:
    needs: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install dependencies
        run: npm ci

      - name: compile
        run: npm run build

  test:
    needs: compile
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm test
