name: Cloud Run CD (prod)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_PROD }}
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  GCP_SA: ${{ secrets.GCP_SA_PROD }}
  RUN_REGIONS: europe-north1,asia-northeast1,europe-west1,us-central1,southamerica-east1
  IMAGE: ${{ github.event.repository.name }}

jobs:
  setup-publish-deploy:
    name: Setup, build image, publish and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '328.0.0'
          service_account_key: $GCP_SA
          project_id: $PROJECT_ID
      - name: Install Google Cloud SDK Beta components
        run: yes | gcloud components install beta --quiet
      - name: Set service version
        run: echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Configure Google Container Registry credentials
        run: gcloud --quiet auth configure-docker
      - name: Build image
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$RELEASE_VERSION" \
            --build-arg DEPLOY_KEY="$DEPLOY_KEY" \
            --build-arg GCP_SA="$GCP_SA" \
            .
      - name: Publish image
        run: docker push "gcr.io/$PROJECT_ID/$IMAGE:$RELEASE_VERSION"
      - name: Expand service manifest with env vars
        run: envsubst < service.yml > prod_service.yaml
      - name: Deploy image to Cloud Run
        run: |-
          IFS=',' read -r -a regions <<< "$RUN_REGIONS"
          for region in "${regions[@]}"; do
            gcloud beta run services replace prod_service.yaml \
            --quiet \
            --region "$region" \
            --platform "managed"
          done
